#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_TYPING_HEATMAP

#ifdef ENCODER_ENABLE
#undef ENCODER_A_PINS
#undef ENCODER_B_PINS
#undef ENCODER_RESOLUTIONS
#undef ENCODER_A_PINS_RIGHT
#undef ENCODER_B_PINS_RIGHT
#undef ENCODER_RESOLUTIONS_RIGHT

#define ENCODER_A_PINS { }
#define ENCODER_B_PINS { }
#define ENCODER_RESOLUTIONS { }
#define ENCODER_A_PINS_RIGHT { F5 }
#define ENCODER_B_PINS_RIGHT { F4 }
#define ENCODER_RESOLUTIONS_RIGHT { 4 }
#endif

