CONVERT_TO=blok

VIA_ENABLE = yes
ENCODER_MAP_ENABLE = yes
SPLIT_KEYBOARD = yes
KEYCODE_STRING_ENABLE = yes
WPM_ENABLE = yes
CAPS_WORD_ENABLE = yes

QUANTUM_PAINTER_ENABLE = yes
QUANTUM_PAINTER_DRIVERS += sh1106_i2c
