#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_TYPING_HEATMAP

#ifdef ENCODER_ENABLE
#undef ENCODER_A_PINS
#undef ENCODER_B_PINS
#undef ENCODER_RESOLUTIONS
#undef ENCODER_A_PINS_RIGHT
#undef ENCODER_B_PINS_RIGHT
#undef ENCODER_RESOLUTIONS_RIGHT

#define ENCODER_A_PINS { }
#define ENCODER_B_PINS { }
#define ENCODER_RESOLUTIONS { }
#define ENCODER_A_PINS_RIGHT { F5 }
#define ENCODER_B_PINS_RIGHT { F4 }
#define ENCODER_RESOLUTIONS_RIGHT { 4 }
#endif

// Enable all typing_stats optional features
#define TS_ENABLE_WPM_TRACKING 1
#define TS_ENABLE_EEPROM_STORAGE 1
#define TS_ENABLE_BIGRAM_STATS 1
#define TS_ENABLE_LAYER_TIME 1
#define TS_ENABLE_ADVANCED_ANALYSIS 1
#define TS_AUTO_NEW_SESSION_ON_BOOT 1
