#pragma once

// QMK
#ifdef RGB_MATRIX_ENABLE
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_TYPING_HEATMAP
#define RGB_MATRIX_SLEEP
#endif

#ifdef OLED_ENABLE
#define OLED_TIMEOUT 15000
#endif

#ifdef SPLIT_KEYBOARD
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_WPM_ENABLE
#define SPLIT_ACTIVITY_ENABLE
#endif

#ifdef CAPS_WORD_ENABLE
#define CAPS_WORD_INVERT_ON_SHIFT
#endif

#ifdef ENCODER_ENABLE
#undef ENCODER_A_PINS
#undef ENCODER_B_PINS
#undef ENCODER_RESOLUTIONS
#undef ENCODER_A_PINS_RIGHT
#undef ENCODER_B_PINS_RIGHT
#undef ENCODER_RESOLUTIONS_RIGHT

#define ENCODER_A_PINS { }
#define ENCODER_B_PINS { }
#define ENCODER_RESOLUTIONS { }
#define ENCODER_A_PINS_RIGHT {F5}
#define ENCODER_B_PINS_RIGHT {F4}
#define ENCODER_RESOLUTIONS_RIGHT {4}
#endif
//

// ANIM
#define ANIM_FRAME_MS 80

#define WIDGET_WATCHDOG_TIMEOUT_MS 1000
#define WIDGET_WATCHDOG_GRACE_MS 500
//

// WPM STATS
#undef WPM_BAR_X
#undef WPM_BAR_Y
#undef WPM_BAR_WIDTH
#undef WPM_BAR_HEIGHT

#define WPM_BAR_X 0
#define WPM_BAR_Y 13
#define WPM_BAR_WIDTH 78
#define WPM_BAR_HEIGHT 11
//

// LUMINO
#define LUMINO_HIGH_BRIGHTNESS 0.8
#define LUMINO_LOW_BRIGHTNESS 0.4

#define LUMINO_LONG_TIMEOUT 60000
#define LUMINO_SOON_TIMEOUT 15000
#define LUMINO_TRANSITION 500

#define LUMINO_BOOT_COLOR RGB_RED
//

// ENCODER LED
#define ENCODER_LED_INDEX 65

#undef SPLIT_TRANSACTION_IDS_USER
#define SPLIT_TRANSACTION_IDS_USER ENCODER_LED_SYNC
//
