#pragma once

// QMK
#ifdef RGB_MATRIX_ENABLE
#    define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#    define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_TYPING_HEATMAP
#    define RGB_MATRIX_SLEEP
#endif

#ifdef OLED_ENABLE
#    define OLED_TIMEOUT 15000
#    define OLED_UPDATE_PROCESS_LIMIT 16
#endif

#ifdef CAPS_WORD_ENABLE
#    define CAPS_WORD_INVERT_ON_SHIFT
#endif

#define DYNAMIC_KEYMAP_LAYER_COUNT 3

// ANIM
#define ANIM_FRAME_MS 80

#define WIDGET_WATCHDOG_TIMEOUT_MS 1000
#define WIDGET_WATCHDOG_GRACE_MS 500
//

// WPM STATS
#undef WPM_BAR_X
#undef WPM_BAR_Y
#undef WPM_BAR_WIDTH
#undef WPM_BAR_HEIGHT

#define WPM_BAR_X 0
#define WPM_BAR_Y 13
#define WPM_BAR_WIDTH 78
#define WPM_BAR_HEIGHT 11
//

// LUMINO
#define LUMINO_HIGH_BRIGHTNESS 0.8
#define LUMINO_LOW_BRIGHTNESS 0.4

#define LUMINO_LONG_TIMEOUT 60000
#define LUMINO_SOON_TIMEOUT 15000
#define LUMINO_TRANSITION 500

#define LUMINO_BOOT_COLOR RGB_RED
//
