SRC += anim.c progmem_anim.c

CONVERT_TO = blok
RAW_ENABLE = no
ENCODER_ENABLE = no
ENCODER_MAP_ENABLE = no
SPLIT_KEYBOARD = no
KEYCODE_STRING_ENABLE = yes
WPM_ENABLE = yes
CAPS_WORD_ENABLE = yes
OLED_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = no
TRI_LAYER_ENABLE = no

UNICODEMAP_ENABLE = no
UNICODE_COMMON = no
