#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_TYPING_HEATMAP

#ifdef ENCODER_ENABLE
#undef ENCODER_A_PINS
#undef ENCODER_B_PINS
#undef ENCODER_RESOLUTIONS
#undef ENCODER_A_PINS_RIGHT
#undef ENCODER_B_PINS_RIGHT
#undef ENCODER_RESOLUTIONS_RIGHT

#define ENCODER_A_PINS { }
#define ENCODER_B_PINS { }
#define ENCODER_RESOLUTIONS { }
#define ENCODER_A_PINS_RIGHT { F5 }
#define ENCODER_B_PINS_RIGHT { F4 }
#define ENCODER_RESOLUTIONS_RIGHT { 4 }
#endif

#define WPM_BAR_X 1
#define WPM_BAR_Y 1
#define WPM_BAR_WIDTH 124
#define WPM_BAR_HEIGHT 28

#define SPLIT_WPM_ENABLE

#define SPLIT_TRANSACTION_IDS_USER WPM_STATS_SYNC

